version: "3.9"
services:
  db:
    image: mysql:8.0.35-debian
    container_name: products-backend-db
    ports:
      - "3306:3306"
    restart: always
    enviroment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbuser
      - MYSQL_DATABASE=films
    volumes:
      - ./config/prod/mysql_dump:/docker-entrypoint-init.d
      - mysql-data:/var/lib/mysql #Opcional
    app:
      build: .
      container_name: products-backend-api
      volumes:
        - ./app:/var/www/html/app
        - ./config/prod/virtualhosts/productsmmira.api.chickenkiller.com.conf:/etc/apache2/sites-enabled/products.api.dev.com.conf
      ports:
        - "8080:80"
      restart: always
      depends_on:
        - db
volumes:
  mysql-data: #Opcional (si queremos mantener los datos de la base de datos)